import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nikhil Padiyath Portofolio</title>
        <meta name="description" content="Generated by"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main >
      <section className= "min-h-screen">
        <nav>
          <h1>Nikhil Padiyath</h1>
          <ul>
            <li></li>
            <li><a href="#">Resume</a></li>
          </ul>
        </nav>
        
      </section >
         </main>
    </div>
  )
}
